### ISSUE TITLE
Schemas for Info endpoints

### ISSUE THREAD

**Issue by Tom-Shorter** [ga4gh-beacon/beacon-framework-v2#27]
Schema versions for the query endpoints are well defined in the models repo within the `beaconConfiguration.json` file as well as within the `defaultSchema.json` file for each entry type but the same is not true for the Info endpoints.

`/map` expects a meta section in the response with a requested schemas section, the only mention to the schema version is within the `beaconMapResponse-example.json` file, can the schema versions be included within the response schemas too? In the case of Map that would probably be `beaconMapSchema.json`.

It might also be worth extending the `beaconConfiguration.json` and `beaconMap.json` file within the beacon model to include all endpoints of the beacon, including the info endpoints. This is already the case within the `endpoints.json` file within the model. These files would then include the default schema versions and endpoints.

**Comment by jrambla** [comment]
@Tom-Shorter it seems to me that this issue is no longer valid as I can't find the source of it.
Currently, `BeaconMap `is using the `informationalResponseMeta` section which has no reference to `requestedSchemas`, just to returned schemas.
If the issue is adding `SchemaVersion` to the returnedSchemas section, keep in mind that `SchemaVersion` is just a decoration, a label for readability by the client, and that the actual schema version is in the `referenceToSchemaDefinition` attribute.
About extending the configuration and map to include the informational endpoints, this is something we can further discuss, but they were not included because all of them are mandatory, hence that part would be identical in all Beacon instances.
