### ISSUE TITLE
[suggestion] beaconResultsets.json /  ResultsetInstance simplification

### ISSUE THREAD

**Issue by redmitry** [ga4gh-beacon/beacon-framework-v2#52]
Hello,

There is unnecessary complication in the 
`BeaconResultsetsResponse.response : BeaconResultsets`
`BeaconResultsets.resultSets : ResultsetInstance[]`

This additional level is used to introduce (optional) `$schema` in the `BeaconResultsets`.
The $schema (that defines ty type of the result sets) may be safely moved to the `BeaconResultsetsResponse` object,
while the `response` becomes an array of what is currently `ResultsetInstance` (I would call it as it was before - `BeaconResultset`).

So it will look like:
`BeaconResultsetsResponse.$schema `
`BeaconResultsetsResponse.response : BeaconResultset[]`

Best,

Dmitry

**Comment by jrambla** [comment]
Hmmm.
I will not say that the additional level is to add `$schema`, but to make it coherent with the other responses, which have a `response `element.
As the framework is agnostic to the schema of the payload in `beaconResultsets`, we added the `$schema` in it in order to "force" declaring and schema for the returned payload. But this was not the reason for adding an additional level.
Please reopen the issue if I've missed something in your comment.
