### ISSUE TITLE
Define & document responses for empty queries

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/beacon-framework-v2#61]
It is currently not clear how empty queries should be handled. The assumption by the verifier to get an "all document" response on the entity root w/o parameters is problematic in production settings (i.e. huge datasets, web spiders etc.). OTOH, this behaviour allows for the verification of the response data schema since no knowledge about existing records is needed. See discussion here: https://github.com/ga4gh-beacon/beacon-verifier/issues/4

#### A: Empty requests lead to `False` response

* "additive" query model, i.e. documents are only returned if a query exists and they match
* more secure, less server load, somehow "logical"
* should have additional definition for example documents, for server tests etc.

#### B: Empty requests lead to `ALL` response

* "subtractive" query model, i.e. the normal "all documents at endpoint" are filtered by query parameters & filters (or not, if none)
* empty query shows full document count
* needs more protective measures on the resource implementation side
* easier for testing / verification
* can be documented to have e.g. a limited document response (e.g. one example document, as if paging max set to 1)

We (@progenetix) are fine w/ both options & have them ready... Thanks to @Tom-Shorter for comments in the thread linked above.

**Comment by jrambla** [comment]
IMU we are dealing with two different issues here:

1. How to deal with Beacon instances that prefer not to respond to non-filtering queries?
2. How to allow for compliance checking in that case?

For 1) the current spec is allowing for answering with boolean or count responses if the Beacon instance is not wanting to answer non-filtering request. 
In cases where non-filtered queries are allowed, the default limit is 10, hence only the first page (top 10 results) would be returned back. Remember that `numTotalResults `is not mandatory, hence it could be omitted from the response.
However, for the client, in case a granularity of boolean or count is returned for a details granularity request, it would not be clear that the reason for that response is because the lack of any filter in the request.
And the discussion on allowing `limit=0` (return all results w/o pagination) would still be a potential open end.
To solve this issue, my suggestion is to add a parameter to the Beacon instance configuration like `nonFilteredQueriesAllowed `that would be boolean and with a default value of `true`, to keep compatibility with current spec.

If we agree in that these two aspects could be dealt independently, we can discuss the compliance checking in another issue.

**Comment by mbaudis** [comment]
The problem here is that parameter-free requests (i.e. `/biosamples/` should not result in a response. You cannot deliver anything if no parameter was provided: At least one of `id`, `filters`, or valid `queryParameters` is needed; this is logical just to allow Boolean responses (you cannot let a Beacon respond `exists` if nothing was queried, and especially since the default for `IncludeResultsetResponses` is `HIT` - which cannot be fulfilled w/o some query or filter etc.

There _could_ be an option to specify `IncludeResultsetResponses=ALL` for having a "all data delivery" response, but this is a bit awkward IMO.

So IMO (and as we had implemented before): No query and no filter and no id - except for info responses - should result in errors.

And your point `2.` can be addressed by providing a dedicated test value/query ...; and this could be made a requirement.

**Comment by mbaudis** [comment]
@jrambla ... That being said, I'll follow any well-documented implementation with "local measures"; e.g. right now empty queries such as [progenetix.org/beacon/variants/](https://progenetix.org/beacon/variants/) lead to an example & `exists`. But this isn't very clean, IMO...

**Comment by jrambla** [comment]
BTW, @mbaudis `includeResultsetResponses `is having the "`ALL`" option (has been there since Beacon v1 ;-) )

**Comment by mbaudis** [comment]
@jrambla Sure; but the expected behaviour is to have a query IMO? At least it isn't well defined that this would return something without - one _could_ make this behaviour explicit (like I mention above); so far it isn't AFAIK.

**Comment by mbaudis** [comment]
Solved in yesterday's discussion; staying with "no query => all" and local limiting, e.g. using https://github.com/ga4gh-beacon/beacon-framework-v2/pull/66 or budgeting.
