### ISSUE TITLE
Responses for compliance checking

### ISSUE THREAD

**Issue by jrambla** [ga4gh-beacon/beacon-framework-v2#65]
As discussed aloing other topics (e.g.#61) the mechanism for allowing compliance checking could be improved to make more clear and transparent. 
There are some suggested/possible solutions: 

1. Every Beacon providing an example of an existing (real or fake) entry (e.g. `/biosamples/1`)
2. Adding a parameter to the every query (e.g. `mode=compliance-test`)
3. Agreeing in a id _for all Beacons_ that represents the "fake-testing" entry (e.g. `/biosamples/_test`)

Opinions and/or additional ideas?

**Comment by jrambla** [comment]
Although, so far, I'm not having an strong opinion, it seems to me that option 2 is the more transversal and elegant, specially because, IMO, the fake Id or example doesn't solve the issue when testing lists, that was the source of discussion in #61 (empty queries).

**Comment by mbaudis** [comment]
I am for `1.`, which can be combined w/ `3.`. I.e. it is left to the implementer if the id in the configuration is real or fake, it just has to lead to a response, but w/o prescribing the format of the id. For implementers it is usually better to use a fake/test id, which can then be interpolated.

`2.` can introduce another bag of hurt since you have to specify the expected behaviour; with `1./3.` it is just SOP.

I'm not sure what the issue w/ lists would be? A single biosample request should lead to a resultSetsResponse, too; i.e. a list of 1 `results` (in a list of 1 `resultSets`)?

**Comment by mbaudis** [comment]
Practical issue: Since there are potentially many paths for a given `entryType/{id}` combination it may be good to supply a single or multiple `testIds` which gan then be interpolated into `{id}` - or should this be explicit? We're using `___id___` which is then interpolated server side ...

**Comment by mbaudis** [comment]
In principle decided to have a dedicated test flag/parameter but needs to be defined.

**Comment by jrambla** [comment]
We have opted for the `testMode` parameter.
Therefore, using `testMode=true` should return a test result for any endpoint
